ansible_user: hexlet

datadog_checks:
  process:
    init_config:
    instances:
      - name: ssh
        search_string: ['ssh', 'sshd']
      - name: syslog
        search_string: ['rsyslog']
        cpu_check_interval: 0.2
        exact_match: true
        ignore_denied_access: true

redmine_version: latest
redmine_external_port: 3000
datadog_api_key: "{{ vault_vars.datadog_api_key }}"
app_key: "{{ vault_vars.app_key }}"